[package]
name = "test-project"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
build = "build.rs"

[lib]
name = "test_project"
crate-type = ["dylib"]

[build-dependencies]
neon-build = { workspace = true }

[dependencies]
neon = { workspace = true }
