[package]
name = "aster"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["aster/with-syntex", "syntex_syntax"]
nightly = []

[dependencies]
aster = { version = "*", default-features = false }
syntex_syntax = { version = "*", optional = true }

